{
 "title": "티켓 시스템 대시보드",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "대기열 진입/이탈",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ticket_queue_entrance_total", "legendFormat": "Queue Entrance" },
    { "expr": "ticket_queue_exit_total", "legendFormat": "Queue Exit" }
   ]
  },
  {
   "title": "티켓 예매 성공/실패",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ticket_reservation_success_total",
     "legendFormat": "성공"
    },
    {
     "expr": "ticket_reservation_failure_total",
     "legendFormat": "실패"
    }
   ]
  },
  {
   "title": "티켓 예매 소요 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(method_execution_time_seconds_bucket{method=\"reserve\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(method_execution_time_seconds_bucket{method=\"reserve\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "동시 접속자 수",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ticket_users_concurrent", "legendFormat": "접속자 수" }
   ]
  },
  {
   "title": "HTTP 요청 처리",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"200\"}[1m]))",
     "legendFormat": "성공 요청(200)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status!=\"200\"}[1m]))",
     "legendFormat": "오류 요청(!200)"
    }
   ]
  },
  {
   "title": "결제 성공/실패",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ticket_payment_success_total", "legendFormat": "성공" },
    { "expr": "ticket_payment_failure_total", "legendFormat": "실패" }
   ]
  }
 ]
}